name: Release

on:
  push:
    branches:
      - main
      - ci-releases

  workflow_dispatch:
    inputs:
      name:
        description: "Output artifact and cfe file name"
        default: "legendcity"
        required: true
        type: string

jobs:
  build:
    uses: legendcity/legendcity-1c/.github/workflows/build-cfe.yml@ci-releases
    with:
      name: legendcity

  release:
    needs: build
    uses: legendcity/legendcity-1c/.github/workflows/github-release.yml@ci-releases
    with:
      name: legendcity
